### PR TITLE
Better input box

### PR DESCRIPTION
**Pull request by ZiYueCommentary**
Added home key, end key, and delete key.

Insert key to switch insert mode.

Hold left/right arrow to fast move cursor.

Control + C to copy content of input box.

### CODE REVIEW

**Comment by Jabka666** [comment]
What is ``SelectedLength``? Also I created ``dev`` branch, so make PRs to this branch

**Comment by ZiYueCommentary** [comment]
Original I want make a shift + arrow to select some text, but I give up at last. maybe I forgot delete that.

**Comment by Jabka666** [comment]
image
Because of ``SelectedLength = 0``

**Comment by Jabka666** [comment]
``SelectedLength`` is always 0

**Comment by Jabka666** [comment]
image
Also I got this error when pressed ``DELETE``

**Comment by ZiYueCommentary** [comment]
> image Because of `SelectedLength = 0`

I met this error when i developing too, the problem is selected text may at left of cursor, and maybe at right. this feature is more complex than others.

**Comment by Jabka666** [comment]
image
I think you forgot to use ``Max`` function to prevent negative value

**Comment by ZiYueCommentary** [comment]
:thinking: I think you're right, and i found insert mode wont response for backspace.

**Comment by Jabka666** [comment]
Well, I'm requesting fixes for that

**Pull request merged**
