### PR TITLE
Better error message

### PR DESCRIPTION
**Pull request by ZiYueCommentary**
Although `ErrorLog` does not work perfectly, the error message still can show the latest exception.

you need to download the latest pre-release of blitz3d tss (ziyuecommentary)

### CODE REVIEW

**Comment by Jabka666** [comment]
I don't have Visual to compile this :))

**Comment by ZiYueCommentary** [comment]
I remember i make a new pre-release

**Comment by ZiYueCommentary** [comment]
github told me uploaded, but it didn't, now i upload it, sorry about that

**Comment by ZiYueCommentary** [comment]
by the way, i forget to delete testing lines in `Source Code/Main_Core.bb` in lines 318-320, could you help me delete that?

thank u :DDD

**Comment by Jabka666** [comment]
Something is wrong with the engine. For some reason it crashes without any message after playing 2 mins. Can you check this?

**Comment by Jabka666** [comment]
Yeah, something is wrong with the engine. v1.129 works fine

**Comment by ZiYueCommentary** [comment]
> Yeah, something is wrong with the engine. v1.129 works fine

I'm fingering out why engine throws exceptions all the time

**Comment by ZiYueCommentary** [comment]
I make engine clear error logs when the log is too much, now it should ok.

**Comment by Jabka666** [comment]
The engine is unstable to use. While using v1.129 I had ~ 320 FPS. Now I have ~150

**Comment by Jabka666** [comment]
> I make engine clear error logs when the log is too much, now it should ok.
> 
> please download v1.130-pre again to get the update. ;)

What do you mean by error logs? Maybe I have too much? How can I check them?

**Comment by ZiYueCommentary** [comment]
> > I make engine clear error logs when the log is too much, now it should ok.
> > please download v1.130-pre again to get the update. ;)
> 
> What do you mean by error logs? Maybe I have too much? How can I check them?

when I testing write error logs into files, game just writing the file, and always stuck at 80% in loadingscreen when loading new game, almost all logs show exceptions are thrown from EntityFX.

**Comment by ZiYueCommentary** [comment]
i need to get more checks for this very annoying bug :/

**Comment by ZiYueCommentary** [comment]
sadly ErrorLog() caused so many bugs, so i removed it, now engine saves the latest exception only.

this change won't influence ue mod, now game had 320 FPS

[_release.zip](https://github.com/Jabka666/scpcb-ue-my/files/9948218/_release.zip)

**Pull request merged**
