### PR TITLE
IniControler!

### PR DESCRIPTION
**Pull request by ZiYueCommentary**
Finally i made this :DDDD

This pr removed scpcb's ini system, and replaced them with inicontroler.

i also add `StringToBoolean` function and overridden `IniGetInt` and `IniGetBufferInt` functions, now game can parse "true/false" to 1 or 0.

for scp294's weird construction, I made a special inicontroler for scpcb-ue, this problem is solved perfectly. https://github.com/ZiYueCommentary/BlitzToolbox/blob/ziyue/BlitzToolbox/BlitzToolbox.cpp

maybe this pr need more check, especially for scp294.

### CODE REVIEW

**Comment by Jabka666** [comment]
Good job fella! Thank you very much!

**Comment by Jabka666** [comment]
Can you explain why SCP294.ini uses UTF-8 with BOM?

**Comment by ZiYueCommentary** [comment]
> Can you explain why SCP294.ini uses UTF-8 with BOM?

i didn't change any encoding, maybe github desktop changed encoding when I solving conflicts

**Comment by Jabka666** [comment]
Alright, I will fix that

**Comment by ZiYueCommentary** [comment]
my forum being stored phishing pages by some wordpress plugin, and now my domain is *server hold*. :((

for a time the language selector will be unable to use, but for a little time only

**Pull request merged**
