### PR TITLE
Optimizations for Checkpoint rooms

### PR DESCRIPTION
**Pull request by SnoeGit**

### CODE REVIEW

**Review by Jabka666 — COMMENTED** [review]
Why do we need ``For i = 0 To 1`` line?

**Review by Jabka666 — CHANGES_REQUESTED** [review]
I think this is how it should be optimized
image

**Comment by Jabka666** [comment]
I still don't understand why there is ``For i = 0 To 1`` line. Why do we need to use "TurnCheckpointMonitorsOff" and "UpdateCheckpointMonitors" twice?

**Comment by SnoeGit** [comment]
It's because the doors have the same \Locked states so I changed the need to type a repeat value 8 times down to 4. Not really necessary to have if you don't want the For i = 0 To 1. For the  "TurnCheckpointMonitorsOff" and "UpdateCheckpointMonitors" I think they are for showing the SCP-008 and Surveillance room text on the monitors at different checkpoints. Didn't want to change them in case I break that.

**Comment by Jabka666** [comment]
Why not to use ``For i = 0 To 1`` only for ``\Locked`` states?

**Comment by Jabka666** [comment]
Looks like the game calls this code two times. And why did you make ``Each Events`` loop first instead of checking the room name and distance?
image

**Comment by Jabka666** [comment]
I think this is what you meant
image

**Comment by Jabka666** [comment]
Optimized by myself

**Pull request closed without merging**
